
DROP TABLE IF  EXISTS PLAYERS;
CREATE TABLE PLAYERS
(
	CONTACT_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR (50) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	WEIGHT INT NOT NULL,
	HEIGHT INT NOT NULL
	
	
);

INSERT INTO PLAYERS (FIRST_NAME,LAST_NAME,BIRTH_DATE,WEIGHT,HEIGHT) VALUES ('EVGENYI','MALKIN','15/05/1993','92','195');
INSERT INTO PLAYERS (FIRST_NAME,LAST_NAME,BIRTH_DATE,WEIGHT,HEIGHT) VALUES ('DOMINIK','GASHEK','18/03/1987','96','185');
INSERT INTO PLAYERS (FIRST_NAME,LAST_NAME,BIRTH_DATE,WEIGHT,HEIGHT) VALUES ('ALEXANDER','OVECHKIN','21/10/1984','89','197');
INSERT INTO PLAYERS (FIRST_NAME,LAST_NAME,BIRTH_DATE,WEIGHT,HEIGHT) VALUES ('WAYNE','GRETSKY','25/04/1976','94','193');
INSERT INTO PLAYERS (FIRST_NAME,LAST_NAME,BIRTH_DATE,WEIGHT,HEIGHT) VALUES ('MARIO','LEMJE','15/02/1985','91','190');
INSERT INTO PLAYERS (FIRST_NAME,LAST_NAME,BIRTH_DATE,WEIGHT,HEIGHT) VALUES ('BOBBY','HALL','14/11/1988','94','183');
INSERT INTO PLAYERS (FIRST_NAME,LAST_NAME,BIRTH_DATE,WEIGHT,HEIGHT) VALUES ('MORIS','RISHAR','11/02/1983','90','182');
INSERT INTO PLAYERS (FIRST_NAME,LAST_NAME,BIRTH_DATE,WEIGHT,HEIGHT) VALUES ('RAYMOND','BURK','13/04/1985','97','189');
INSERT INTO PLAYERS (FIRST_NAME,LAST_NAME,BIRTH_DATE,WEIGHT,HEIGHT) VALUES ('KEN','DRAYDEN','12/12/1982','94','199');
INSERT INTO PLAYERS (FIRST_NAME,LAST_NAME,BIRTH_DATE,WEIGHT,HEIGHT) VALUES ('DIKKI','MURE','26/09/1988','99','184');

DROP TABLE IF EXISTS PROPERTIES;
CREATE TABLE  PROPERTIES(
	CONTACT_ID SERIAL,
	PLAYING_NUBMER INT NOT NULL CHECK
	(PLAYING_NUBMER >0 AND PLAYING_NUBMER <=30),
	SKI_SIZE INT NOT NULL CHECK
	(SKI_SIZE >=6 AND SKI_SIZE <=12),
	GAME_POSITION VARCHAR(20) NOT NULL CHECK 
	(GAME_POSITION IN ('ATTACKER','DEFENDER','GOALKEPPER')),
	PLAYING_HAND VARCHAR(20) NOT NULL CHECK
	(PLAYING_HAND IN ('LEFT','RIGHT'))
	 
);
INSERT INTO PROPERTIES (PLAYING_NUBMER,SKI_SIZE,GAME_POSITION,PLAYING_HAND) VALUES ('5','7','DEFENDER','LEFT');
INSERT INTO PROPERTIES (PLAYING_NUBMER,SKI_SIZE,GAME_POSITION,PLAYING_HAND) VALUES ('12','9','GOALKEPPER','RIGHT');
INSERT INTO PROPERTIES (PLAYING_NUBMER,SKI_SIZE,GAME_POSITION,PLAYING_HAND) VALUES ('30','8','ATTACKER','RIGHT');
INSERT INTO PROPERTIES (PLAYING_NUBMER,SKI_SIZE,GAME_POSITION,PLAYING_HAND) VALUES ('15','9','DEFENDER','LEFT');
INSERT INTO PROPERTIES (PLAYING_NUBMER,SKI_SIZE,GAME_POSITION,PLAYING_HAND) VALUES ('4','11','DEFENDER','RIGHT');
INSERT INTO PROPERTIES (PLAYING_NUBMER,SKI_SIZE,GAME_POSITION,PLAYING_HAND) VALUES ('5','8','DEFENDER','LEFT');
INSERT INTO PROPERTIES (PLAYING_NUBMER,SKI_SIZE,GAME_POSITION,PLAYING_HAND) VALUES ('16','10','ATTACKER','RIGHT');
INSERT INTO PROPERTIES (PLAYING_NUBMER,SKI_SIZE,GAME_POSITION,PLAYING_HAND) VALUES ('11','9','ATTACKER','RIGHT');
INSERT INTO PROPERTIES (PLAYING_NUBMER,SKI_SIZE,GAME_POSITION,PLAYING_HAND) VALUES ('21','7','ATTACKER','RIGHT');
INSERT INTO PROPERTIES (PLAYING_NUBMER,SKI_SIZE,GAME_POSITION,PLAYING_HAND) VALUES ('2','6','ATTACKER','RIGHT');

DROP TABLE IF EXISTS SALARIES;
CREATE TABLE  SALARIES(
	CONTACT_ID SERIAL,
	CONSTANT_PAYMENT INT DEFAULT 7500,
	PRIZE INT,
	FINE INT
);
INSERT INTO SALARIES (PRIZE,FINE) VALUES (1500,1000);
INSERT INTO SALARIES (PRIZE,FINE) VALUES (1500,1000);
INSERT INTO SALARIES (PRIZE,FINE) VALUES (1500,1000);
INSERT INTO SALARIES (PRIZE,FINE) VALUES (1500,1000);
INSERT INTO SALARIES (PRIZE,FINE) VALUES (1500,1000);
INSERT INTO SALARIES (PRIZE,FINE) VALUES (1500,1000);
INSERT INTO SALARIES (PRIZE,FINE) VALUES (1500,1000);
INSERT INTO SALARIES (PRIZE,FINE) VALUES (1500,1000);
INSERT INTO SALARIES (PRIZE,FINE) VALUES (1500,1000);
INSERT INTO SALARIES (PRIZE,FINE) VALUES (1500,1000);

DROP TABLE IF EXISTS GAME;
CREATE TABLE  GAME(
	CONTACT_ID SERIAL,
	GOALS INT,
	ASSISTS INT,
	PENALTY_TIME REAL CHECK
	(PENALTY_TIME <= PLAYING_TIME),
	PLAYING_TIME REAL CHECK
	(PLAYING_TIME <=60)
	
);
INSERT INTO GAME (GOALS,ASSISTS,PENALTY_TIME,PLAYING_TIME) VALUES ('5','12','3.5','15.3');
INSERT INTO GAME (GOALS,ASSISTS,PENALTY_TIME,PLAYING_TIME) VALUES ('0','3','5.2','6.2');
INSERT INTO GAME (GOALS,ASSISTS,PENALTY_TIME,PLAYING_TIME) VALUES ('0','0','0','60');
INSERT INTO GAME (GOALS,ASSISTS,PENALTY_TIME,PLAYING_TIME) VALUES ('12','5','2','36');
INSERT INTO GAME (GOALS,ASSISTS,PENALTY_TIME,PLAYING_TIME) VALUES ('1','3','1.3','24.7');
INSERT INTO GAME (GOALS,ASSISTS,PENALTY_TIME,PLAYING_TIME) VALUES ('0','5','0','42');
INSERT INTO GAME (GOALS,ASSISTS,PENALTY_TIME,PLAYING_TIME) VALUES ('7','2','4.5','53.2');
INSERT INTO GAME (GOALS,ASSISTS,PENALTY_TIME,PLAYING_TIME) VALUES ('0','7','3.2','33.8');
INSERT INTO GAME (GOALS,ASSISTS,PENALTY_TIME,PLAYING_TIME) VALUES ('4','9','0','26.8');
INSERT INTO GAME (GOALS,ASSISTS,PENALTY_TIME,PLAYING_TIME) VALUES ('0','0','0','0');

SELECT  PLAYERS.CONTACT_ID, PLAYERS.FIRST_NAME,PLAYERS.LAST_NAME, PROPERTIES.GAME_POSITION,
PROPERTIES.PLAYING_NUBMER,SALARIES.CONSTANT_PAYMENT,GAME.PLAYING_TIME
FROM PLAYERS 
INNER JOIN PROPERTIES ON  PLAYERS.CONTACT_ID = PROPERTIES.CONTACT_ID
INNER JOIN SALARIES ON PLAYERS.CONTACT_ID = SALARIES.CONTACT_ID
INNER JOIN GAME ON PLAYERS.CONTACT_ID = GAME.CONTACT_ID



